export const GET_BEERS = 'GET_GET_BEERS';
export const ADD_BEER_TO_CART = 'ADD_BEER_TO_CART';
export const REMOVE_BEER_FROM_CART = 'REMOVE_BEER_FROM_CART';
export const ON_EMPTY_CART = 'ON_EMPTY_CART';
export const UPDATE_CART_QTY_PLUS = 'UPDATE_CART_QTY_PLUS';
export const UPDATE_CART_QTY_MOINS = 'UPDATE_CART_QTY_MOINS';
